module.exports.authController = require('./auth.controller')
module.exports.userController = require('./user.controller')
module.exports.messageController = require('./message.controller')
module.exports.topicController = require('./topic.controller')
module.exports.threadController = require('./thread.controller')
module.exports.pollController = require('./poll.controller')
module.exports.exportController = require('./export.controller')
